### ISSUE TITLE
[BUG] Nightly build triggers off PR

### ISSUE THREAD

**Issue by jiata** [microsoft/computervision-recipes#302]
### Description
Just checking, but these lines (https://github.com/microsoft/ComputerVision/blob/3eab18177620cb15f18afd8e9cb02c63da1deba1/.ci/AML-nightly-gpu.yml#L35-L37) should not appear in the nightly build ci yaml file right? We shouldn't be triggering out nightly build off a PR.

### In which platform does it happen?
CICD

**Comment by bethz** [comment]
There was a devops bug where CRON was not working properly. So, initially, I added the PR trigger because of that so we can ensure that builds happen. I'll check if cron is working again.

**Comment by PatrickBue** [comment]
@jiata Can this be closed, given that Young made significant changes to the devops pipelines?
