### ISSUE TITLE
[BUG] fixes with detection plotting methods

### ISSUE THREAD

**Issue by jiata** [microsoft/computervision-recipes#341]
### Description

Should only use one plotting function, etc. 

- [ ] right now in 01 notebook `plot_grid(plot_detection_vs_ground_truth, …)` does not output label name (and should output score) but `display_bboxes()` outputs label name (and should output rounded score) 
- [ ] `show_ims()` can be very pixelated and label hard/impossible to read 
- [ ] Color-code: use different color for drawing rectangles for different classes

**Comment by PatrickBue** [comment]
Another point: even when setting cols=1, the images are still small and the label sometimes not readable. The image when setting cols=1 could fill out more (or the full) notebook width.

**Comment by PatrickBue** [comment]
Closing this, since already in PR
