### ISSUE TITLE
Maybe remove predict_batch function

### ISSUE THREAD

**Issue by PatrickBue** [microsoft/computervision-recipes#366]
Not sure if the predict_batch() is necessary. It has the same inputs and outputs as predict_dl(), so maybe combine both functions into one (called predict_dl to be consistent with fastai)

**Comment by jiata** [comment]
This was my initial reason for having it.

![image](https://user-images.githubusercontent.com/16616215/67954048-a8775500-fbc6-11e9-932c-7f3c9f1e2c6e.png)

**Comment by PatrickBue** [comment]
Do we think this overflow of memory is ever a problem? Bounding boxes (and segmentation masks) shouldn't take up much space I guess.

**Comment by PatrickBue** [comment]
Closing since this comment was already addressed (predict_batch is moved into text, but not executed as code anymore)
