### ISSUE TITLE
[FEATURE_REQUEST] Add some images with multiple objects from the same category

### ISSUE THREAD

**Issue by simonzhaoms** [microsoft/computervision-recipes#376]
### Description

When I want to use the odFridgeObjects dataset in object detection to explain the difference between semantic segmentation and panoptic segmentation, I need an image with multiple objects from the same category, e.g., an image of two water bottles and one milk bottle, instead of an image of only one object from arbitrary category.

### Expected behavior with the suggested feature

* An image of multiple water bottles and 1 milk bottle
* An image of multiple water bottles and multiple milk bottles
* An image of multiple milk bottles and 1 water bottle
* An image of multiple cartons and 1 milk bottle
...

### Other Comments

Not sure if this kind of images would be helpful in other aspects.

**Comment by jiata** [comment]
can we do this digitally for now?

**Comment by simonzhaoms** [comment]
Good idea :+1: 
I can write a script to programmatically synthesize images by putting individual objects together. :smile: 
And this would be helpful for annotation.  Annotation is a painful experience.
