### ISSUE TITLE
[BUG] Link to "notebooks" is broken in SETUP.md

### ISSUE THREAD

**Issue by mawah** [microsoft/computervision-recipes#397]
### Description

At the end of the "Installation" section (before the pip install subsection), there is a link to the notebooks in the repository: https://github.com/microsoft/ComputerVision/blob/master/SETUP.md#scenarios. However, there is no "scenarios" section in SETUP.md so the link fails.

### In which platform does it happen?
All.

### How do we replicate the issue?
Click that link in SETUP.md.

### Expected behavior (i.e. solution)
Add a relevant section to SETUP.md, or give a recommendation on where to begin with the notebooks (like a link to a specific file).

**Comment by PatrickBue** [comment]
Thanks. Fixed this now in a PR, and will go into staging/master soon.
