### ISSUE TITLE
[BUG] 00_webcam.ipynb - webcam widge does not show

### ISSUE THREAD

**Issue by YanZhangADS** [microsoft/computervision-recipes#402]
### Description
webcam widge does not show in 00_webcam.ipynb for object detection

### In which platform does it happen?
Ubuntu DSVM NC6
Chrome/Firefox/Edge
I use port forward to this DSVM from my laptop. My laptop has windows system.

### How do we replicate the issue?
Nothing happens after executing cell:
HBox([w_cam, w_imrecorder, w_im])

### Expected behavior (i.e. solution)
the webcam widget should show in the notebook

**Comment by jiata** [comment]
check if page as camera access: https://smartserve.zendesk.com/hc/en-us/articles/360012330533-How-do-I-check-my-browser-permissions-for-my-camera-and-microphone-

**Comment by PatrickBue** [comment]
Closing since we made changes a while back to make the widget rendering more stable
