### ISSUE TITLE
[BUG] consider to re-wording 12_hard_negative_sampling.ipynb

### ISSUE THREAD

**Issue by YanZhangADS** [microsoft/computervision-recipes#413]
### Description
Please consider re-wording "the model over-fires heavily, i.e. it detects objects where none are." in detection/12_hard_negative_sampling.ipynb

I still don't get what is the problem to tackle.

"over-fire" is used in later section as well. Therefore please define it in a way that is more formal and technically sound.

**Comment by PatrickBue** [comment]
We did a complete overhaul of the wording in this notebook.
