### ISSUE TITLE
[ASK] Update references for detection

### ISSUE THREAD

**Issue by jiata** [microsoft/computervision-recipes#414]
Update references for detection: https://github.com/pytorch/vision/tree/master/references/detection

**Comment by PatrickBue** [comment]
@jiata What do you mean by that? Is one possible way forward to delete the python examples in this readme?
https://github.com/pytorch/vision/tree/master/references/detection

**Comment by PatrickBue** [comment]
Closing since we updated the object detection references directory recently.
