### ISSUE TITLE
[BUG] dummy negative sampling for mask

### ISSUE THREAD

**Issue by simonzhaoms** [microsoft/computervision-recipes#426]
### Description

in `_read_annos()` of `utils_cv/detection/dataset.py`, a dummy tiny bounding box is added when negative sample is allowed, so correspondingly a dummy mask is added in `_get_binary_mask()` of `utils_cv/detection/dataset.py`.  However, this dummy mask is not fully tested yet.

### In which platform does it happen?

All.

### Expected behavior (i.e. solution)

Need to test the dummy mask make sense and won't have bad impact on the prediction.

**Comment by PatrickBue** [comment]
Closing since we test this in our unit and integration tests.
