### ISSUE TITLE
[FEATURE_REQUEST] Provide links for papers in contrib/action_recognition

### ISSUE THREAD

**Issue by sharatsc** [microsoft/computervision-recipes#455]
### Description
List of papers in https://github.com/microsoft/ComputerVision/tree/master/contrib/action_recognition is currently a PNG file. 

### Expected behavior with the suggested feature
Provide links to arxiv instead

**Comment by PatrickBue** [comment]
Done. Moved the table to the readme in CVBP core and added links:
https://github.com/microsoft/computervision-recipes/tree/master/scenarios/action_recognition
