### ISSUE TITLE
fastai v2 doest not have DatasetType

### ISSUE THREAD

**Issue by puneethmishra** [microsoft/computervision-recipes#531]
This command does not work in FastAI version 2.
from fastai.vision import DatasetType, open_image

please do let us know the alternative

**Comment by PatrickBue** [comment]
We currently do not support fastai v2 since it is still being developed. Instead, we assume version 1.0.57 (see the environment.yml) file, but our code should also work with the latest official fast.ai [release](https://github.com/fastai/fastai/releases) (1.0.60)

**Comment by puneethmishra** [comment]
Thanks. Is the role of DatasetType more to split the data into training and testing
What so the role of DatasetType.fix?

**Comment by PatrickBue** [comment]
DatasetType is defined by fast.ai and only used in this repo. See e.g. here:
https://docs.fast.ai/basic_data.html#DatasetType

**Comment by Saeed0Baba** [comment]
I have the same problem.

DatasetType is not defined

is there any solution?

**Comment by pmeleney** [comment]
> I have the same problem.
> 
> DatasetType is not defined
> 
> is there any solution?

I got around this problem by not installing pytorch first, and allowing fastai to install torch for me as part of it's installation.  Looks like torch version 1.9.0 and torchvision version 0.10.0. Hope that helps.
