### ISSUE TITLE
[ASK]action recognition i3d pretrained model link invalid

### ISSUE THREAD

**Issue by sunnymoon155** [microsoft/computervision-recipes#542]
### Description

wget https://har.blob.core.windows.net/i3dmodels/flow_hmdb_split1.pt
wget https://har.blob.core.windows.net/i3dmodels/rgb_hmdb_split1.pt
wget https://har.blob.core.windows.net/i3dmodels/flow_imagenet_kinetics.pt
wget https://har.blob.core.windows.net/i3dmodels/rgb_imagenet_kinetics.pt
### Other Comments
Could you please help to check the link?

**Comment by lilisako** [comment]
I'm having same issue here✋

**Comment by PatrickBue** [comment]
Thanks for filing this issue. We are currently cleaning up the action recognition code, adding daily unit-tests, etc. The work is nearly done and in the "jiata-new-dataset" branch, with all notebooks under /scenarios/action_recognition/. That code should work.
@jiata

**Comment by lilisako** [comment]
Thanks for letting us know! I'll check it out and look forward to new update on this repository!

**Comment by PatrickBue** [comment]
The action recognition implementation is now finished and in master, which fixes this issue
