### ISSUE TITLE
cannot import name 'show_batch' from 'utils_cv.action_recognition.dataset'

### ISSUE THREAD

**Issue by shulavkarki** [microsoft/computervision-recipes#554]
### Description
File directory is well placed. HELP?

**Comment by ShroukMansour** [comment]
I faced the same problem, but it runs well in 02_training_hmdb.ipynb file

**Comment by PatrickBue** [comment]
We nearly finished polishing up the action recognition scenario. It currently is in the staging branch. Have a look here, the code should be fully functional:
https://github.com/microsoft/computervision-recipes/tree/staging/scenarios/action_recognition

**Comment by PatrickBue** [comment]
The action recognition work is now done and in master, which should fix this issue.
