### ISSUE TITLE
CUDA out of memory. Tried to allocate 36.00 MiB (GPU 0; 4.00 GiB total capacity; 2.88 GiB already allocated; 627.20 KiB free; 2.95 GiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by shulavkarki** [microsoft/computervision-recipes#561]
### Description
I having problem with my CUDA.? Any Help is greatly appreciated?

**Comment by PatrickBue** [comment]
Try reducing the batch size or the image size or both. That way the model should fit into memory.

**Comment by shulavkarki** [comment]
Thank you!
