### ISSUE TITLE
Examples for Stereo vision

### ISSUE THREAD

**Issue by jeffin07** [microsoft/computervision-recipes#580]
### Description
Examples for stereo vision like depth-map creation,3D reconstruction using two or more cameras etc

### Expected behavior with the suggested feature
Most of the cv libraries have Stereo examples.It will be good if you have stereo examples.like creating depth map and 3d reconstruction using two or more cameras(Left and Right images)

**Comment by PatrickBue** [comment]
Thanks for the feedback, we'll put Stereo on our backlog.
