### ISSUE TITLE
What is the version requirement of torch?

### ISSUE THREAD

**Issue by Joboing** [microsoft/computervision-recipes#610]

**Comment by Joboing** [comment]
Hi，I want to know the version requirement of torch.

**Comment by PatrickBue** [comment]
The recommended version can be seen in the environment.yml file (pytorch==1.2.0) but somewhat newer or older versions should work as well:
https://github.com/microsoft/computervision-recipes/blob/master/environment.yml

**Comment by PatrickBue** [comment]
Closing issue now since the question seems to be addressed.
