### ISSUE TITLE
[ASK]I can not find ItemList from fastai.vision.

### ISSUE THREAD

**Issue by btdan** [microsoft/computervision-recipes#615]
### Description

in the file **computervision-recipes/utils_cv/classification/data.py**  
include one line as follows:
**_from fastai.vision import ItemList_**
but there are not ItemList in the source code of fastai
Is there any reason?
Thanks very much

**Comment by JunnYu** [comment]
you should install fastai v1
pip install fastai==1.0.61
```
import fastai
print(fastai.__version__) # 1.0.61
from fastai.vision import ItemList
```

**Comment by btdan** [comment]
Thanks very much, It works well.
