### ISSUE TITLE
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1 [ASK]

### ISSUE THREAD

**Issue by starsky68** [microsoft/computervision-recipes#617]
### Description

This error appears when running sh make.sh

error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

**Comment by PatrickBue** [comment]
Please make sure nvcc from Nvidia is installed. E.g. https://stackoverflow.com/questions/56470424/nvcc-missing-when-installing-cudatoolkit

**Comment by PatrickBue** [comment]
Closing this comment due to inactivity.
