### ISSUE TITLE
I also encountered the same problem, how can I solve it？

### ISSUE THREAD

**Issue by hinoryu** [microsoft/computervision-recipes#619]
I also encountered the same problem, how can I solve it？

__Originally posted by @isangmeng in https://github.com/electron/electron/issues/20299#issuecomment-688119278__

**Comment by PatrickBue** [comment]
Can you please add some information how this is related to this repository, e.g. where does the bug appear.

**Comment by PatrickBue** [comment]
Closing since this does not seem to be relevant for this repository.
