### ISSUE TITLE
### Description ###

### ISSUE THREAD

**Issue by alayham2** [microsoft/computervision-recipes#620]
### Description ###
If an invalid XML is passed to jQuery.parseXML, currently the thrown parse error only contain the input data but not the error reason.
However the internally created XML document contains the parser errors in the element parsererror as innerText and could be added. This is helpful for debugging errors in XML files

### Link to test case ###
https://jsfiddle.net/o678xuz3/

__Originally posted by @MatthiasSchmalz in https://github.com/jquery/jquery/issues/4784__

**Comment by PatrickBue** [comment]
Looks like this is a bug in an external library? If so, could you please close here since this is not in our code base.

**Comment by PatrickBue** [comment]
Closing since this issue is already tracked in the external library.
