### ISSUE TITLE
save model error

### ISSUE THREAD

**Issue by sam0983** [microsoft/computervision-recipes#622]
### Description
Hi, thank you for the great work! In the action recognition repository, when I set save_model = True, I encounter the following error in the model.py file on line 278:
KeyError: 'self'

why is this? thank you

**Comment by PatrickBue** [comment]
Thanks. This is a known bug, which is fixed in the staging branch (removed "self."). See this PR here:
https://github.com/microsoft/computervision-recipes/pull/616/files

**Comment by sam0983** [comment]
got it thanks!
