### ISSUE TITLE
What is utils_cv ? 

### ISSUE THREAD

**Issue by VinayChaudhari1996** [microsoft/computervision-recipes#626]
I m trying to execute .ipynb code in Google colab , everytime I'm facing issue of utils_cv.

Can you locate that (utils_cv) file ? Or 
How can I fix it ? 

Thanks ,

**Comment by PatrickBue** [comment]
utils_cv is the main library and needs to be imported. See implementation here:
https://github.com/microsoft/computervision-recipes/tree/master/utils_cv

**Comment by tytung2020** [comment]
Hi could you share the codes to import the main library to colab? thanks
