### ISSUE TITLE
> Version: 1.9.1

### ISSUE THREAD

**Issue by MuhammadJahanara-1995** [microsoft/computervision-recipes#645]
> Version: 1.9.1
> 
> 
> 
> Crash on BFTask Init method on line 54
> 
> 
> 
> ```
> 
>  _callbacks = [NSMutableArray array];
> 
> ```
> 
> 
> 
> Maybe this should be 
> 
> 
> 
> ````
> 
>  _callbacks = [[NSMutableArray alloc] init];
> 
> ````
> 
> 
> 
> Crash info:
> 
> ````
> 
>  Heap corruption detected, free list is damaged at 0x2814a8cc0 *** Incorrect guard value: 8081049728
> 
> ````
> 
> 
> 
> strack trace
> 
> ```
> 
> Crashed: com.parse.asynctaskqueue.sync
> 
> 0  libsystem_kernel.dylib         0x1b70da95c __pthread_kill + 8
> 
> 1  libsystem_pthread.dylib        0x1d237e9e8 pthread_kill + 212
> 
> 2  libsystem_c.dylib              0x1952cb934 abort + 100
> 
> 3  libsystem_malloc.dylib         0x19af9d030 _malloc_put + 554
> 
> 4  libsystem_malloc.dylib         0x19af9d2a4 malloc_zone_error + 100
> 
> 5  libsystem_malloc.dylib         0x19af9d2e0 nanov2_allocate_from_block$VARIANT$mp.cold.1 + 36
> 
> 6  libsystem_malloc.dylib         0x19af82428 nanov2_find_block_and_allocate$VARIANT$mp + 510
> 
> 7  libsystem_malloc.dylib         0x19af816a0 nanov2_allocate$VARIANT$mp + 124
> 
> 8  libsystem_malloc.dylib         0x19af81b90 nanov2_calloc$VARIANT$mp + 148
> 
> 9  libsystem_malloc.dylib         0x19af92aa4 _malloc_zone_calloc + 80
> 
> 10 libobjc.A.dylib                0x19ff024bc class_createInstance + 52
> 
> 11 CoreFoundation                 0x18c65d84c __CFAllocateObject + 20
> 
> 12 CoreFoundation                 0x18c573710 __NSArrayM_new + 56
> 
> 13 CoreFoundation                 0x18c53ea2c +[NSArray array] + 32
> 
> 14 Bolts                          0x106888e20 -[BFTask init] + 54 (BFTask.m:54)
> 
> 15 Bolts                          0x1068877f8 -[BFTaskCompletionSource init] + 37 (BFTaskCompletionSource.m:37)
> 
> 16 Bolts                          0x1068877a4 +[BFTaskCompletionSource taskCompletionSource] + 30 (BFTaskCompletionSource.m:30)
> 
> 17 Bolts                          0x10688a99c -[BFTask continueWithExecutor:block:cancellationToken:] + 322 (BFTask.m:322)
> 
> 18 Bolts                          0x10688a910 -[BFTask continueWithExecutor:withBlock:] + 316 (BFTask.m:316)
> 
> 19 Parse                          0x105da50d0 -[BFTask(Private) continueAsyncWithBlock:] + 33 (BFTask+Private.m:33)
> 
> 20 Parse                          0x105d42570 __28-[PFAsyncTaskQueue enqueue:]_block_invoke + 50 (PFAsyncTaskQueue.m:50)
> 
> 21 libdispatch.dylib              0x18c289298 _dispatch_call_block_and_release + 24
> 
> 22 libdispatch.dylib              0x18c28a280 _dispatch_client_callout + 16
> 
> 23 libdispatch.dylib              0x18c232fa8 _dispatch_lane_serial_drain$VARIANT$mp + 612
> 
> 24 libdispatch.dylib              0x18c233a84 _dispatch_lane_invoke$VARIANT$mp + 424
> 
> 25 libdispatch.dylib              0x18c23d518 _dispatch_workloop_worker_thread + 712
> 
> 26 libsystem_pthread.dylib        0x1d237f5a4 _pthread_wqthread + 272
> 
> 27 libsystem_pthread.dylib        0x1d2382874 start_wqthread + 8
> 
> ```

__Originally posted by @MuhammadJahanara-1995 in https://github.com/BoltsFramework/Bolts-ObjC/issues/344#issuecomment-804182341__

**Comment by PatrickBue** [comment]
Closing this issue since it was posted already in Bolts-ObjC and not code written in this repo.
