### ISSUE TITLE
[ASK] action recognition milk bottle example

### ISSUE THREAD

**Issue by georgecloudservices** [microsoft/computervision-recipes#650]
### Description
I am trying to reproduce your example with milk bottle videos but with other two actions. So I put in 2 folder the actions exactly like your example but after some time I get error

    [h264 @ 0x5589e4916040] mmco: unref short failure
    raise DECORDError(py_str(_LIB.DECORDGetLastError()))
    decord._ffi.base.DECORDError: [17:31:57] /io/decord/src/video/video_reader.cc:90: Check failed: st_nb >= 0 (-1381258232 vs. 0) ERROR cannot find video stream with wanted index: -1

Any idea why this happens? I think the problem has to do with __getitem__ in this line https://github.com/microsoft/computervision-recipes/blob/7a97689264989727a8ae28d87496346389a44019/utils_cv/action_recognition/dataset.py#L512
and with decord

Thanks!

**Comment by PatrickBue** [comment]
My best guess would be that the videos have an encoding that Decord doesn't understand. Maybe try converting one to a common encoding and then try again. Also make sure there's no special characters in the filenames, just in case.

**Comment by georgecloudservices** [comment]
Thanks for your help! Indeed some videos were wrongly cutted!
