### ISSUE TITLE
[ASK] Batch Sampler and extreme classification 

### ISSUE THREAD

**Issue by kifjj** [microsoft/computervision-recipes#662]
### Description

Hi @PatrickBue  thanks for the similarity source code, very useful to see the implementation of such an important paper.
I have a question, the paper mentions Subsampling for Classification Scalability and in the case of the SOP Dataset I think we are in extreme classification situation. 
You didn't implement that and still replicate the performance, do you have any explanation? Do you think that implementing subsampling would be beneficial for other datasets with 27k classes?

Thanks
#

**Comment by PatrickBue** [comment]
Hi, I don't fully remember the details of the paper hence don't know the answer. Maybe the original authors of the paper/code would know: https://github.com/azgo14/classification_metric_learning

**Comment by kifjj** [comment]
Thanks for the reply @PatrickBue.
